mbf8exact: mbf8exact.o quicklist.o mbf6.o swap.o
	g++ mbf8exact.o quicklist.o mbf6.o swap.o -O3 -o mbf8exact
mbf8exact.o: mbf8exact.cpp
	c++ -c -O3 mbf8exact.cpp
quicklist.o: quicklist.cpp
	c++ -c -O3 quicklist.cpp
mbf6.o:
	c++ -c -O3 mbf6.cpp
swap.o:
	c++ -c -O3 swap.cpp